# Generated by Django 5.1.1 on 2025-06-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_files',
            name='File_Type',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
    ]
