# Generated by Django 5.1.1 on 2025-06-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_tbl_files_file_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_files',
        ),
    ]
