# Generated by Django 5.1.1 on 2025-06-17 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convert', '0003_delete_tbl_files'),
        ('user', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(blank=True, null=True, upload_to='')),
                ('Upload_Date', models.DateField(null=True)),
                ('File_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('File_Type', models.CharField(max_length=20)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbl_users')),
            ],
        ),
    ]
