# Generated by Django 5.1.1 on 2025-06-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_files',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
