# Generated by Django 5.1.1 on 2025-06-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0005_tbl_files_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_files',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='converted/'),
        ),
    ]
