# Generated by Django 5.1.1 on 2025-06-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_users',
        ),
    ]
