# Generated by Django 5.1.1 on 2025-06-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_users',
            old_name='profile_pic',
            new_name='Profile_pic',
        ),
        migrations.RemoveField(
            model_name='tbl_users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tbl_users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tbl_users',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tbl_users',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='tbl_users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tbl_users',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='tbl_users',
            name='Fist_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tbl_users',
            name='Email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tbl_users',
            name='Last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tbl_users',
            name='Mobile',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_users',
            name='Password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
