# Generated by Django 5.1.1 on 2025-06-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_profile_pic_tbl_users_profile_pic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_users',
        ),
    ]
