# Generated by Django 5.1.1 on 2025-06-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_delete_tbl_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30, null=True)),
                ('Last_name', models.CharField(max_length=30, null=True)),
                ('Email', models.EmailField(max_length=30, null=True)),
                ('Mobile', models.IntegerField(null=True)),
                ('Password', models.CharField(max_length=128, null=True)),
                ('Profile_pic', models.ImageField(blank=True, null=True, upload_to='static/profile_pics')),
            ],
        ),
    ]
