# Generated by Django 5.1.1 on 2025-06-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_users',
            name='Reg_date',
            field=models.DateField(null=True),
        ),
    ]
