# Generated by Django 5.1.1 on 2025-06-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tbl_users_reg_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=150)),
                ('Message', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
